pipeline {
    agent any

    stages {
        stage('Build') {
		    agent {
                label 'Grd-Mvn'
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
        stage('Test') {
            agent {
                label 'Grd-Mvn'
            }
			steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                label 'Grd-Mvn'
            }
			steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}




