pipeline {
    agent any

    stages {
        stage('Git-Checkout') {
            agent {
                label 'Grd-Mvn'
            }
            steps {
                checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/naveen4141/Simple-Maven.git']]]
						
            }
        }
    }
    stages {
        stage('Build') {
		    agent {
                label 'Grd-Mvn'
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            agent {
                label 'Grd-Mvn'
            }
			steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                label 'Grd-Mvn'
            }
			steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}




